permissions:
  contents: write

name: Publish Release

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - name: Publish framework-dependent
        run: dotnet publish IbrahKit_MailClient.csproj -c Release -r win-x64 `
              -p:PublishSingleFile=true `
              -p:SelfContained=false `
              -p:AssemblyName=IbrahKit_MailClient-framework-dependent `
              -o publish/framework-dependent

      - name: Publish self-contained
        run: dotnet publish IbrahKit_MailClient.csproj -c Release -r win-x64 `
              -p:PublishSingleFile=true `
              -p:SelfContained=true `
              -p:AssemblyName=IbrahKit_MailClient-self-contained `
              -o publish/self-contained

      - name: Upload release assets
        uses: softprops/action-gh-release@v2
        with:
          files: |
            publish/framework-dependent/*.exe
            publish/self-contained/*.exe
